# Deloppgave 4: Studiedesign

<!-- Part 4: Study designs -->

## Introduksjon

I denne oppgaven har jeg valgt fem originale artikler hvor jeg skal se på styrkene og svakhetene omhandlet studienes design og valg av statistiske tester. De fem valgte studiene omhandler muskelkvalitet (MK) innenfor styrketrening. Hvor godt en muskel klarer å løse en oppgave i forhold til størrelsen samt kvaliteten på muskelen sier noe om muskelkvaliteten. Muskelkvalitet er definert som styrke per enhet muskelmasse.[@Ivey2000]. Begrepene muskelkvalitet og spesifikk spenning har lik betydning i denne oppgaven.

## Metode

*Formål*

Formålet til alle artiklene er innenfor tematikken styrketreningens påvirkning på muskelkvalitet. I studien av Ivey (2000) er formålet å se på alders- og kjønnssammenhenger i responsen av styrketrening på muskelkvaliteten. Dette for å avgjøre om det er andre faktorer enn muskelmasse som påvirker styrke økninger eller tap av styrke hos unge og eldre menn og kvinner[@Ivey2000]. I studien av Ferrari (2016) er formålet å sammenligne effekten av ulik ukentlig frekvens av samme trening og se på muskelkraft og muskelkvalitet[@ferrari2016]. Pinto (2014) har som formål å vurdere effekten av et kortvarig styrketreningsprogram på muskelkvaliteten og funksjonskapasitet[@Pinto2014]. Videre har studien til Erskine (2011) som formål å finne ut om en forventet økning i muskelspesifikk spenning (MK) etter styrketrening kan forklares av endringer i muskelens isoformsammensetning og enkeltfiberspesifikk spenning eller en endring i lateral kraftoverføring[@Erskine2011]. Siste valgte studie av Tracy (1999) har som formål å sammenligne responsen på muskelkvalitet på en unilateralt quadriceps styrketreningsprogram mellom eldre menn og eldre kvinner[@Tracy1999].

*Hypoteser*

Tre av fem artikler har en tydelig hypotese før datainnsamling, mens de resterende to artiklene tar mer for seg spørsmål innenfor temaet, som igjen er en av grunnene til at de har startet studien. Hypotesene er hovedsakelig basert på tidligere kunnskap og tidligere studier. De studiene som hadde en tydelig hypotese kan i følge Hulley (2013) kategoriseres under kliniske studier. Kliniske studier har en mal hvor det å danne flere gode hypoteser på forhånd for å deretter spesifisere en primær hypotese er sentral. Det positive med å ha en primær hypotese er at det kan bli lettere å fokusere innsamlingen av dataen på de faktorene/variablene som kan tilknyttes hypotesen[@designin2013, s.53]. Ferrari (2016) er et eksempel på en studie som hadde en klar hypotese som var basert på tidligere innsamlinger av data i andre studier og handlet om at styrketrening utført to eller tre ganger i uken vil gi lik muskeltilpasning. Et eksempel på en studie som hadde spørsmål istedenfor hypoteser var Ivey (2000) der de ønsker å få svar på om alder eller kjønn påvirker MK og hva som skjer etter opphør av styrketrening, og om nedgang i muskelaktivitet bidrar til aldersrelatert nedgang av MK.

*Rekrutering av deltakere*

Metoden de ulike studiene brukte for å rekruttere deltakerne til studiene var tilnærmet likt. Grunnlaget for alle studiene var at deltakerne fikk god informasjon om studiene i forkant, de måtte gi skriftlig samtykke, det var frivillig og alle hadde gjennomgått en sykehistorikk og hatt fysiske undersøkelser. Alle studiene har også blitt godkjent av ulike universitet og medisinske senter. Forskjellene mellom studiene var at noen hadde litt ulike krav i forholdt til om deltakerne skulle være utrente eller trente og graden av erfaring i forkant, noe som står beskrevet i studiene. Populasjonen eller deltakerne i alle studiene er beskrevet med alder ± x år og kjønn. Det er også informert om hvordan de har utelukket deltakere grunnet deres ulike sykdommer, medisiner eller fysiske plager. Fire av fem studier tar for seg en populasjon over 65 år hvor den ene studien har deltakere i alder rundt 20 år.

*Statistiske metoder*

Samtlige studier har en pre og en post test hvor testingen er lik med blant annet samme utstyr, samme tid på døgnet, samme forsker og lik tid mellom øvelsene. De bruker derimot ulikt statistiske tester for å se forskjellene fra før og etter intervensjonen med styrketrening. Studiene av Ivey (2000) og Tracy (1999) tar MR av quadriceps både pre-test og post-test, samt 1RM av kneekstensjon. Erskine (2011) tester også 1RM av kneekstensjon og tar MR, samt muskelbiopsi og anatomisk tverrsnittsarial kalt «ACSA» for å estimere MK i quadricepsen. Studiene av Ferrari (2016) og Pinto (2014) tar ultralyd av muskeltykkelse, samt 1RM av kne-/beinekstensjon. Bare studiene av Ivey (2000), Ferrari (2016) og Tracy (1999) nevnte at de hadde utprøving av testingen i forkant for å unnvike læringseffekten og for å forebygge skader. Dette kan imidlertidig også føre til redusert størrelse på forandringene på pre-test og post-test, da de får testet ut øvelsene før testen starter.

Variasjonsanalysen kalt «ANOVA» var den statistiske analysen som ble tatt i bruk i samtlige studier. Ferarri (2016, Ivey (2000) og Pinto (2014) tok i bruk to-veis ANOVA som sammenligner to uavhengige variabler mens Erskine(2010) og Tracy (1999) brukte en annen versjon av toveis ANOVA som kalles repeterte målinger hvor de sammenligner en eller flere variabler som er basert på repeterende observasjoner. I dette tilfellet sammenlignes pre-tester og post-tester i ulike grupper. Fordelen med toveis ANOVA ovenfor enveis ANOVA er at man kan undersøke effekten av to variabler samtidig. Studien av Ferrari (2016) hadde også en crossover randomisert klinisk studie hvor deltakerne ble tilfeldig delt inn i 2 grupper. Deltakerne skulle dermed enten trene to ganger i uken eller tre ganger i uken. Begge gruppene hadde samme intensitet og volum under treningene til tross for ulike treningsdager, samt tett veiledning av minst to erfarne personlige trenere. Ferrari (2016), Tracy (1999) og Pinto (2014) brukte progrmavarepakken "Statistical Package of the Social Sciences" (SPSS), versjon 17.0, for statistiske beregninger av data. Den statistiske metoden for beregning av data var ikke nevnt i studiene av Ivey(2000) og Erskine(2010).

Ivey (2000), Pinto (2014), Erskine (2011) og Tracy (1999) har tatt i bruk p-verdi hvor samtlige hadde et signifikansnivå under 0.05 (P \< 0.05). Ferrari (2016) tok i bruk alpha for å vise til at studien var signifikant ved a= 0.05. Både Erskine (2011) og Ferrari (2016) hadde også tatt i bruk t-test for å sammenligne belastningene før og etter styrketreningen for hver pulje.

## Resultat

Til tross for at alle studiene hadde ulik tilnærming i form av antall repetisjoner og serier, samt ulik kombinasjon av antall deltakere, alder og kjønn, fikk alle et resultat som indikerer en viss prosent økning i MK etter styrketrening. Alle som hadde en klar hypotese, fikk enten bekreftet eller avkreftet den etter datainnsamlingen. Til tross for dette fikk ikke alle studiene svar på alt de lurte på.

Artikkelen av Ferrari (2016) hadde en klar hypotese i forkant av studien og fikk til resultat at styrketrening utført to ganger i uka ga 8% økning i MK sammeligent med styrketrening tre ganger i uken som ga 15% økning i MK[@ferrari2016]. Studien av Pinto (2014) hadde en hypotese som ble bekreftet som handlet om at seks ukers styrketrening vil resultere i markerte gevinster innenfor muskeltykkelse og MK [@Pinto2014]. Hypotesen til studien av Tracy (1999) viste seg å være feil da det ikke var en betydelig forskjell mellom kjønn på MK[@Tracy1999]. Spørsmålet i artikkelen av Erskine (2011) ble besvart med at muskelspesifikk spenning øker etter styrketrening hvorav et eksempel på en av de mulige årsakene var at det var en økning i lateral kraftoverføring fra sarkomerer i muskelfibrene. Et eksempel på et spørsmål de ikke fikk svar på var om det var noen sammenheng mellom isoformsammensetning og økning i muskelspesifikk spenning[@Erskine2011]. Studien av Ivey (2000) hadde blant annet spørsmål angående kjønns- og aldres påvirkning på MK, hvor resultatet tyder på at det er økning i MK i begge kjønn både hos unge og eldre[@Ivey2000].

*Vedlagt er en tabell over alle studiene hvor informasjon om deltakerne, studiedesign og resultat er representert.*

+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+
|            | Studie                 | Deltakere                                     | Studiedesign                                        | Resultat                                                                                    |
+============+========================+===============================================+=====================================================+=============================================================================================+
| 1\.        | Ivey, et al. (2000)    | 42 deltakere:\                                | 9 uker styrketrening og 31 ukers "nedtrapping":     | Økning i muskelkvalitet blant unge og gamle (begge kjønn)                                   |
|            |                        | Unge menn og kvinner og eldre menn og kvinner |                                                     |                                                                                             |
|            |                        |                                               | 5-10 reps\                                          |                                                                                             |
|            |                        | 20-30 år og 65-75 år                          | 5 serier\                                           |                                                                                             |
|            |                        |                                               | 3 ganger i uka                                      |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | Bein- og kneekstensjon                              |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | MR.                                                 |                                                                                             |
+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+
|            |                        |                                               |                                                     |                                                                                             |
+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+
| 2\.        | Ferrari, et al (2016)  | 24 deltakere:\                                | 20 uker trening og 10 uker intervensjon:            | -   2 ganger i uka:\                                                                        |
|            |                        | Eldre trente menn                             |                                                     |     8% økning i MK                                                                          |
|            |                        |                                               | 8-12 reps\                                          |                                                                                             |
|            |                        | 65±4 år                                       | 3 serier\                                           | -   3 ganger i uka:\                                                                        |
|            |                        |                                               | 2 eller 3 ganger i uka (2 ulike grupper)            |     15% økning i MK                                                                         |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | Beinekstensjon                                      |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | Ultralyd.                                           |                                                                                             |
+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+
|            |                        |                                               |                                                     |                                                                                             |
+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+
| 3\.        | Pinto, et al. (2014)   | 36 deltakere:\                                | 6 uker:                                             | 15% økning i MK i quadriceps                                                                |
|            |                        | Eldre kvinner                                 |                                                     |                                                                                             |
|            |                        |                                               | 12-15 reps\                                         |                                                                                             |
|            |                        | 66±8 år                                       | 2-3 serier\                                         |                                                                                             |
|            |                        |                                               | 2 ganger i uka                                      |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | Kneekstensjon                                       |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | Ultralyd.                                           |                                                                                             |
+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+
|            |                        |                                               |                                                     |                                                                                             |
+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+
| 4\.        | Erskine, et al. (2011) | 42 deltakere:\                                | 9 uker:                                             | 11% økning i MK (spesifikk tensjon)                                                         |
|            |                        | Unge menn                                     |                                                     |                                                                                             |
|            |                        |                                               | 10 reps\                                            |                                                                                             |
|            |                        | 20 ±3 år                                      | 4 serier\                                           |                                                                                             |
|            |                        |                                               | 80%av 1RM\                                          |                                                                                             |
|            |                        |                                               | 3 ganger i uka                                      |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | bein-og kneekstensjon                               |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | MR.                                                 |                                                                                             |
+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+
|            |                        |                                               |                                                     |                                                                                             |
+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+
| 5\.        | Tracy, et al. (1999)   | 23 deltakere:\                                | 9 uker:                                             | Betydelig økning i MK i begge gruppene                                                      |
|            |                        | 12 eldre menn og 11 eldre kvinner             |                                                     |                                                                                             |
|            |                        |                                               | 5 serier:\                                          | Ingen kjønnsforksjeller i MK hos eldre; de foreslår nevromuskulære årsaker i begge gruppene |
|            |                        | 65-75 år                                      | -1: oppvarming, 5 rep (50% av 1RM)\                 |                                                                                             |
|            |                        |                                               | -2: 5 rep (5RM)\                                    |                                                                                             |
|            |                        |                                               | -3: 10 reps (5 rep på 5RM og 5 rep på mindre vekt)\ |                                                                                             |
|            |                        |                                               | -4 og 5: 5 rep (5RM) + 10 rep (som nr.3)\           |                                                                                             |
|            |                        |                                               | 3 ganger i uka                                      |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | Kneekstensjon + 1RM i kneekstensjon                 |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | MR.                                                 |                                                                                             |
+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+
|            |                        |                                               |                                                     |                                                                                             |
+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+

## Diskusjon

Samtlige studier konkluderte, som sagt tidligere, at det er en tydelig økning i muskelkvalitet etter styrketrening. I tabellen ovenfor vises alle resultatene fra studiene, og ut ifra tabellen kan vi se at styrketrening med mellom 8-15 reps, 3 serier og 2-3 ganger i uka ga en positiv innvirkning på muskelkvaliteten. Det kom også frem at alle deltakerne uavhengig av kjønn og alder fikk økt muskelkvalitet. P-verdien på \<0.05 og alpha på \<0.05 indikerer at det er under 5% sannsynlig for at resultatene i alle studiene er tilfeldige. Det kan derimot være vanskelig å konkludere med hvilke antall repetisjoner og serier som er optimalt for hver gruppe med tanke på å øke muskelkvaliteten da alle studiene har ulikt antall. Til videre forskning ville det derfor kanskje vært interresant å undersøke om hvilke sammensetning av repetisjoner og serier som gir mest økning i muskelkvalitet.

De studiene som hadde en hypotese i forkant, tok denne med inn i resultat og diskusjonsdelen. Det var både bekreftelser og avkreftelser av hypoteser. Det var ikke alle studiene som hadde lagt fram ønske om videre forskning i diskusjonsdelen. Studiene av Ivey (2000) og Tracy (1999) la blant annet frem at de ikke fant noen tydelig forskjell på økt muskelkvalitet mellom kjønn og Ferrari (2016) kunne konkludere med at det var tilnærmet lik økning i muskelkvalitet om du trente to eller tre dager i uka. Studien av Pinto (2014) legger fram resultat om økt muskelkvalitet hos eldre kvinner etter et kortvarig styrketreningsprogram. Da flertallet av studiene har deltakere på 65+ kan vi dermed tolke resultatenen som at aldersrelaterte plager spille inn på motivasjonen og tidsbruk. Resultatene indikerer at eldre menn og kvinner behøver bare å trene to ganger i uka, samt at to treninger i uka gir rask forbedring. Dette kan øke motivasjonen og muligheten for å vedlikeholde styrken, da styrke er veldig viktig for eldre mennesker å vedlikeholde for å kunne utføre daglige aktiviteter og gjøremål.[@ferrari2016; @Pinto2014]. Erskine (2011) var den eneste av studiene som hadde deltakere som var unge, og i dette tilfellet menn, hvor resultatet viste til en økning i muskelkvalitet og muskelstyrke. Til tross for det ble musklene samtidig langsommere. Resultatet omhandlet at musklene ble langsommere uttrykker Erskine (2011) nødvendigheten med ytterligere arbeid for å kunne forklare resultatet.[@Erskine2011].

Alle studiene hadde en god beskrivelse av deltakerne som var med, samt hvem de hadde utelatt grunnet fysiske utfordringer. Alle deltagerne hadde fått god og rikelig med informasjon i forkant av studien. Begrunnelsene for valg av alder i studiene hadde sterk sammenheng med hypotesen i forkant av datainnsamlingene. Som tidligere nevnt hadde fire av studiene deltakere på 65+ år, og alle konkluderte med at det som kommer med alderdommen kan påvirke styrken og muskelkvaliteten [@ferrari2016; @Ivey2000; @Pinto2014; @Tracy1999]. Denne studien tar for seg et bredt spekter av deltakere fra 20 år til 65+ noe som fører til at vi kan få mer informasjon om hvordan styrketrening påvirker ulike aldre. Til tross for dette kunne en lignenede studie som denne med få innhentete originale studier, gitt en mer nøyaktig beskrivelse av styrketreningens påvirkning på MK på én aldersgruppe hvis alle studiene hadde deltakere som var innenfor omtrent samme alder. Studiene hadde et antall deltakere fra 23 til 42. En større andel deltakere kunne med fordel gitt større statistisk styrke, grunnet flere observasjoner som kan påvirke studienes resultater.

For at videre undersøkelser skal kunne få best mulig svar på lignende spørsmål som de nevnte studiene, vil blant annet det å arbeide nøyaktig i gjennomføringen av testene og eventuelt lab arbeid være viktig, samt standardisere protokollene slik at gjennomføringen er mest mulig likt for hver gang for at testene skal kunne være reliabel. I alle studiene var MR og ultralyd den statistiske metoden for å måle muskelkvalitet pre-test og post-test. To av fem studier har benyttet ultralyd som statistisk test og tre av fem studier brukte MR. Man kan i større grad skille mellom muskulatur, fettvev og andre vev med MR enn ultralyd, noe som kan gi et mer nøyaktig og konkret svar. Da en MR tar mer nøyaktige bilder i forhold til tema omhandlet muskelkvalitet kan den gi et mer konkret svar og det vil sannsynligvis bli mindre målefeil og andre feilmarginer. Jeg har fått inntrykk av at alle studiene har hatt god planlegging og gjennomføring med tanke på reliabilitet og validitet da det var like pre- og post-tester, og de ble gjennomført på tilnærmet lik måte. Ut ifra studiene jeg har valgt fikk de med hypotese et tydeligere svar enn de som bare hadde spørsmål da den enten blir bekreftet eller avkreftet. Derfor mener jeg at det er en fordel å ha en tydelig hypotese før innsamling av data for å kunne systematisere data og ha mer fokus på variabler tilknyttet hypotesen.
