# Deloppgave 3: Vitenskapsfilosofi

<!-- Part 3: Philosophy of science -->

### 1. Falsifikasjonisme

*Hva er Poppers falsifiserbarhetskriterium og hvilket spørsmål skal dette kriterium gi svar på? Hvorfor mener andre vitenskapsfilosofer (f.eks. Okasha) at vi ikke trenger å svare på dette spørsmålet? Hvem synes dere har rett?*

Okasha (2016) forteller om Popper og hans tanker om at det som gjør en teori vitenskapelig er at den er falsifiserbar [@okasha, s.13]. Det at en teori er falsifiserbar betyr at forutsigelsene i en teori kan bli testet mot data, altså at det er mulig å påvise at teorien er gal. Strukturen til Poppers falsifiseringskriterium består av at man utarbeider en hypotese ut ifra en teori. Hvis dataen ikke passer med forutsigelsene i teorien, vil teorien bli falsifisert eller motbevist. (F. Dellsén, Vitenskapelige argument, 2022). En teori som er ufalifiserbar vil passe inn i alle mulige empiriske observasjoner, samt det ikke vil finnes forutsigelser som kan testes mot dataen. Dersom dataene ikke passer med forutsigelsene, vil ikke denne teorien kunne falisifiseres og testes mot data. Hvis en teori ikke er falsifiserbar mente Popper at teoriene var pseudovitenskapelig, altså uvitenskapelige. [@okasha, s.13]. Poppers falsifiserbarhetskriterium skal derfor gi svar på om en teori er vitenskapelig eller uvitenskapelig (F. Dellsén, Vitenskapelige argument, 2022). Popper mente det var en sterk linje mellom uvitenskapelige og vitenskapelige teorier, samt at vitenskapelige teorier ikke kunne bli bekreftet bare falsifisert. Ved tankegangen om å ikke behøve å bekrefte teorier, men bare falsifisere teorier mente Popper at induksjonsproblemet kunne unngås. (F. Dellsén, Vitenskapelige argument, 2022). Induksjonsproblemet handler kort sagt om hvordan en skal begrunne gyldigheten til teorier [@okasha, s. 28].

Andre vitenskapsfilosofer mener at det ikke er en sterk linje mellom vitenskapelige og uvitenskapelige teorier, hvor viktigheten av forskjellene mellom en godt bekreftet teori og en dårlig bekreftet teori er sentralt (F. Dellsén, Vitenskapelige argument, 2022). Okasha (2016) viser til en tankegang hvor målet med vitenskapen ikke er bare å motbevise teorier som Popper mente, men også danne teorier som er mest sannsynlig sanne. Han mente at det var mer sannsynlig å prøve å bevise at deres egen teori var sann og dermed bruke induktive argument. I tillegg er nesten alle teorier innenfor vitenskapen i konflikt med noen observerte data, og det er ekstremt vanskelig å finne teorier hvor all data passer perfekt. Det ville da vært ekstremt liten fremgang innenfor forskning hvis alle la vekk teorien sin ved litt motstand. [@okasha, s.16]. Videre argumenterer Okasha (2016) med en metafor hvor man kan erstatte ordet «spill» med «vitenskap» i eksempelet fra Ludwig Wittgenstein som lyder slik; spill kan ikke defineres med et enkelt kriterium for å skille hva som er spill og ikke, og spill kan ha mange ulike former, hvorav alt likevel kan være spill. [@okasha, s.17].

Jeg syntes det er utfordrende å velge hvem som har rett. Poppers falsifiseringskriterium viser til en enkel og klar måte for å skille vitenskap og uvitenskap på. I tillegg unngår man induksjonsproblemet, som kan være en stor fordel. Samtidig mener jeg at det er uheldig å eliminere alt som ikke kan falsifiseres da det ville vært lite fremgang innen forskning hvis alt som møtte motstand ble eliminert. I og med at alle har gode argumenter, kommer jeg ikke fram til en avgjørelse om hvem jeg syntes har rett.

### 2. Hypotetiske deduktive metoden og abduksjon

*Hva er strukturen på et bekreftende vitenskapelig argument ifølge den hypotetisk deduktive metode? Forklar ut fra Hempels artikkel, men bruk egne eksempel. Sammenlign også Hempels HD-metode med hvordan vitenskapelig bekreftelse fungerer ifølge enten abduksjon eller Bayesianisme.*

Den hypotetiske deduktive metoden, HD-metoden, er et bekreftende vitenskapelig argument bestående av fire trinn der idéen er å bekrefte en teori ved å få positive resultater gjennom testing av teoriens deduktive konsekvenser (Hempel, 1966). HD-metoden går derfor ut på å trekke egne beslutninger ut ifra hypotesen hvor hypotesen blir bekreftet ved positive resultater/data. (F. Dellsén, Abduksjon og sannsynlighet, 2022). Trinn en handler om å formulere en hypotese eller teori. Videre omhandler trinn to av strukturen om å utvinne empiriske konsekvenser fra den satte teorien eller hypotesen ved deduksjon. (F. Dellsén, Abduksjon og sannsynlighet,
2022). Videre i trinn tre skal de empiriske konsekvensene testet i observasjon eller i et eksperiment. Dersom de empiriske konsekvensene visere seg å være riktig via observasjon eller eksperimenter vil teorien bekreftes av dataen til en viss grad ved induksjon. Hvis de empiriske konsekvensene ikke er riktig, blir teorien falsifisert. (F. Dellsén, Abduksjon og sannsynlighet, 2022). Siste trinn består av å finne ut om de empiriske konsekvensene er riktige. Hempel påpeker likevel at selv om mange empiriske konsekvenser av en hypotese blir funnet gjennom nøye testing, kan hypotesen likevel være feil. (F. Dellsén, Abduksjon og sannsynlighet, 2022). Et forenklet eksempel på HD-metoden er å formulere en hypotese eller teori som «hvordan vet vi at proteiner har en positiv effekt på muskelvekst?» I trinn to ser vi på de empiriske konsekvensene som ville da vært at proteiner blir omgjort til aminosyrer som kroppen bruker for å bygge muskler. Via observasjoner og/eller eksperimenter i trinn tre vil vi både se at proteiner blir omgjort til aminosyrer og at kroppen bruker det til å bygge opp musklene. Dermed kan vi ved induktiv bekreftelse si at protein har en positiv effekt på muskelvekst. (F. Dellsén, Abduksjon og sannsynlighet, 2022).

En annen vitenskapelig bekreftelse man kan sammenligne HD-metoden med er abduksjon (F. Dellsén, Abduksjon og sannsynlighet, 2022). Abduksjon går ut på å ta utgangspunkt i flere teorier for deretter å forklare hvilke observasjoner man tror skal skje. Etter det skal man bekrefte teoriene induktivt ved å sammenligne teoriene og hvor godt hver av teoriene forklarer de ulike observasjonene. Abduksjon krever at en teori forklarer dataen, hvorav ingen av teoriene gir en bedre forklaring enn de andre tilgjengelige alternative teoriene. (F. Dellsén, Abduksjon og sannsynlighet, 2022).

Abduksjon ligner på den hypotetisk deduktive metoden, men forskjellene mellom HD-metoden og abduksjon er at man i abduksjon ser på flere ulike teorier som forklarer det samme fenomenet, men HD-metoden ser kun på én teori. Altså, i abduksjon har vi flere teorier som forklarer dataene, hvor dataene bekrefter teorien(e). I HD-metoden starter man med å argumentere før en teori hvor dataen bekrefter teorien til en viss grad. (F. Dellsén, Abduksjon og sannsynlighet, 2022). Ved abduksjon sammenlignes de ulike teoriene og den som gir mest mening ut ifra dataene velges [@okasha, s. 29]. Hvilken teori man velger i abduksjon kan bli en subjektiv avgjørelse derav egne erfaringer og observasjoner ligger til grunn for bestemmelsen [@okasha, s.33]. Abduksjon vil ha et stort fokus på å unngå deduksjon. HD-metoden kan derimot både være deduktiv og induktivt. Det kan forklares ved at prosessen starter deduktivt ved at man har en teori som man samler inn data mot, deretter kan dataen induktivt bekrefte teorien tilbake. Ved å danne empiriske konsekvenser som kan forskes på videre prøver abduksjon å induktivt bekrefte teorier til en viss grad. (F. Dellsén, Abduksjon og sannsynlighet, 2022).

### 3. Replikasjonskrisen

*Hva mener Alexander Bird er forklaringen til at mange resultat i noen vitenskaper ikke repliseres? Oppsummere Birds argument for dette. Sammenlign også Birds forklaring med noen av de andre forklaringene som Bird diskuterer i seksjon 4. Har Bird rett i at hans forklaring er bedre?*

Replikasjon handler om å gjøre en undersøkelse på nytt for å sjekke om det tidligere forskningsresultatet gjentar seg, eller er tilnærmet likt. Replikasjonskrisen beskriver utfordringen med at mange forskningsresultater i mange vitenskaper ikke er repliserbare. (F. Dellsén, Sannsynlighet og replikasjonskrisen, 2022). Krisen kan forklares ved at det finnes tvilsomme forskningspraksiser med fabrikkering og juks, for lav statistisk styrke med for få forsøkspersoner og/eller publikasjonsskevhet hvor negative resultater ikke blir publisert i likhet med resultater som er positive (F. Dellsén, Sannsynlighet og replikasjonskrisen, 2022). + [@bird2021, seksjon 1]. Replikasjonskrisens påvirkning på økt mistillit til vitenskapen som tilhører andre felt enn der krisen oppstår er en bekymring [@bird2021, seksjon 2].

Et av argumentene Bird tar for seg omhandlet replikasjonskrisen er basefrekvensfeilen [@bird2021, seksjon 1]. Bird (2018) uttrykker at basefrekvensfeilen skjer ved at man trekker en konklusjon om sannsynligheten for en bestemt forekomst av et fenomen, hvor man fokuserer på et bevis og utelukker sannsynligheten for at det fenomenet kan skje uavhengig av beviset. Dette kan resultere i ukorrekte konklusjoner. [@bird2021, seksjon 1.2]. Bird (2018) legger frem argumentet med forsking med lav p-verdi, som omhandler sannsynligheten for å få et falskt positivt resultat, altså å akseptere en usann teori (F. Dellsén, Sannsynlighet og replikasjonskrisen, 2022). Bird (2018) forteller også om utfordringer om forskning som viser seg å være falsk positiv, der flere andre forskningsprosjekter er basert på det falske positive resultatet. I mange tilfeller vil de nye hypotesene som prøves å lages være parallelt med den gamle hypotesen og dens baktanke som fører til at den nye også kan bli usann. [@bird2021, seksjon 3.1]. Videre forteller Bird at selv om hypotesen blir laget på en godkjent måte, vil ikke det automatisk gi en hypotese høy sannsynlighet for at den er sann. I tillegg påstår han at noen hypoteser fra ulike kilder kan være en årsak til forskning som produserer falske hypoteser. [@bird2021, seksjon 3.1].

En undersøkelse viste at en årsak til at det er forskning som ikke er realiserbare er at de følte på et press for å publisere og utfordringer med å replisere forskningen på deres lab [@bird2021, seksjon 4]. Dette kan føre til forskning som ikke er gjennomtenkt eller ikke har mulighet til å fullføre den på en gunstig måte. Deltakerne i undersøkelsen nevnte derimot ikke lav p-verdi som Bird har antydet er kan være en årsak tidligere i artikkelen.[@bird2021, seksjon 4].

Videre i artikkelen har andre uttrykt at lav statisk styrke er med på replikasjonskrisen [@bird2021, seksjon 4.1]. Statisk styrke er sannsynligheten for at en test gir resultat som gjør at man avviser en usann nullhypotese. Altså at et større antall deltakere i forskingsprosjekter styrker sannsynligheten for å ikke få en type II feil, et falskt negativt resultat (F. Dellsén, Sannsynlighet og replikasjonskrisen, 2022). Bird (2018) uttrykker uenighet rundt dette og mener at det forekommer type II feil selv ved høy statisk styrke. Til tross for dette mener Bird (2018) at en økt statisk styrke innenfor vitenskapen vil være ha en positiv innflytelse, men det vil ikke være en løsning på krisen. [@bird2021, seksjon 4.1]. Det blir også diskutert om Bird er enig i at publikasjonsskjevhet er en god grunn nok i seg selv for å påvirke replikasjonskrisen. Bird uttrykker uenighet i dette i og med at hypoteser da bare blir testet hvis de har en solid teoretisk støtte samtidig som de eliminerer falske hypoteser. Dette kan føre til at de vil anse en positiv hypotese som sann, noe den ikke alltid er. Dette kan da resultere i en produksjon av mange falske positive tester. [@bird2021, seksjon 4.2]. Bird (2018) avslutter med å si at det ikke er nok bevis på å trekke en konklusjon rundt tema om replikasjon og selv om man følger reglene og har lav p-verdi kan man få falske positive resultater og dermed mange mislykkede replikasjoner. [@bird2021, seksjon 4.3].  

Jeg mener at Bird har mange gode argumenter som kan være årsak til replikasjonskrisen deriblant basefrekvesfeilen og falske positive resultater. Likevel vil jeg også si meg enig i mange av de andres teorier om årsaker til krisen som nevner lav statisk styrke og dårlig praksis og juks. Dette fører meg til en konklusjon hvor jeg ikke syntes at Bird alene har rett.
